image: node:8.11.1

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@7.1.0
  - npm install
  - npm run build:prod
  - npm run build
  - mv dist/junte-ui-app/* public/
  artifacts:
    paths:
    - public
  only:
  - master
